version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: kPEx69012024
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql